---
title: "rchime"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rchime}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rchime)
```

Description of rchime package

## Getting started with `{rchime}`
To get started you'll need to install `{rchime}` using either of these commands:

```{r, eval = FALSE}
# devtools::install_github("mothur/rchime") #install development version
# install.packages("rchime") # install stable version from CRAN
```

To get access to the packages function and a demonstration version of the sequence data, you'll need to run the `library()` function. 

```{r setup}
library(rchime)
```

## Creating a dataset object

```{r}
dataset <- sequence_data_vector(filename = rchime_example("test.fasta"))
dataset$set_group_assignments(filename = rchime_example("test.count_table"))
dataset
```


## Removing chimeras denovo

```{r}
chimera_uchime(dataset, dereplicate = TRUE)
dataset
```

## Removing chimeras by reference

```{r}
dataset <- sequence_data_vector(filename = rchime_example("test.fasta"))
dataset$set_group_assignments(filename = rchime_example("test.count_table"))
dataset
chimera_uchime(dataset, reference = rchime_example("reference.fasta"))
dataset
```

