// Generated by /p/py/alphac.py
#include "alpha.h"

unsigned g_CharToLetterNucleo[256] =
	{
	INVALID_LETTER, // [  0] = 0x00
	INVALID_LETTER, // [  1] = 0x01
	INVALID_LETTER, // [  2] = 0x02
	INVALID_LETTER, // [  3] = 0x03
	INVALID_LETTER, // [  4] = 0x04
	INVALID_LETTER, // [  5] = 0x05
	INVALID_LETTER, // [  6] = 0x06
	INVALID_LETTER, // [  7] = 0x07
	INVALID_LETTER, // [  8] = 0x08
	INVALID_LETTER, // [  9] = 0x09
	INVALID_LETTER, // [ 10] = 0x0a
	INVALID_LETTER, // [ 11] = 0x0b
	INVALID_LETTER, // [ 12] = 0x0c
	INVALID_LETTER, // [ 13] = 0x0d
	INVALID_LETTER, // [ 14] = 0x0e
	INVALID_LETTER, // [ 15] = 0x0f
	INVALID_LETTER, // [ 16] = 0x10
	INVALID_LETTER, // [ 17] = 0x11
	INVALID_LETTER, // [ 18] = 0x12
	INVALID_LETTER, // [ 19] = 0x13
	INVALID_LETTER, // [ 20] = 0x14
	INVALID_LETTER, // [ 21] = 0x15
	INVALID_LETTER, // [ 22] = 0x16
	INVALID_LETTER, // [ 23] = 0x17
	INVALID_LETTER, // [ 24] = 0x18
	INVALID_LETTER, // [ 25] = 0x19
	INVALID_LETTER, // [ 26] = 0x1a
	INVALID_LETTER, // [ 27] = 0x1b
	INVALID_LETTER, // [ 28] = 0x1c
	INVALID_LETTER, // [ 29] = 0x1d
	INVALID_LETTER, // [ 30] = 0x1e
	INVALID_LETTER, // [ 31] = 0x1f
	INVALID_LETTER, // [ 32] = 32
	INVALID_LETTER, // [ 33] = 33
	INVALID_LETTER, // [ 34] = 34
	INVALID_LETTER, // [ 35] = 35
	INVALID_LETTER, // [ 36] = 36
	INVALID_LETTER, // [ 37] = 37
	INVALID_LETTER, // [ 38] = 38
	INVALID_LETTER, // [ 39] = 39
	INVALID_LETTER, // [ 40] = 40
	INVALID_LETTER, // [ 41] = 41
	INVALID_LETTER, // [ 42] = 42
	INVALID_LETTER, // [ 43] = 43
	INVALID_LETTER, // [ 44] = 44
	INVALID_LETTER, // [ 45] = 45
	INVALID_LETTER, // [ 46] = 46
	INVALID_LETTER, // [ 47] = 47
	INVALID_LETTER, // [ 48] = 48
	INVALID_LETTER, // [ 49] = 49
	INVALID_LETTER, // [ 50] = 50
	INVALID_LETTER, // [ 51] = 51
	INVALID_LETTER, // [ 52] = 52
	INVALID_LETTER, // [ 53] = 53
	INVALID_LETTER, // [ 54] = 54
	INVALID_LETTER, // [ 55] = 55
	INVALID_LETTER, // [ 56] = 56
	INVALID_LETTER, // [ 57] = 57
	INVALID_LETTER, // [ 58] = 58
	INVALID_LETTER, // [ 59] = 59
	INVALID_LETTER, // [ 60] = 60
	INVALID_LETTER, // [ 61] = 61
	INVALID_LETTER, // [ 62] = 62
	INVALID_LETTER, // [ 63] = 63
	INVALID_LETTER, // [ 64] = 64
	0  ,            // [ 65] = A (Nucleotide)
	INVALID_LETTER, // [ 66] = 66
	1  ,            // [ 67] = C (Nucleotide)
	INVALID_LETTER, // [ 68] = 68
	INVALID_LETTER, // [ 69] = 69
	INVALID_LETTER, // [ 70] = 70
	2  ,            // [ 71] = G (Nucleotide)
	INVALID_LETTER, // [ 72] = 72
	INVALID_LETTER, // [ 73] = 73
	INVALID_LETTER, // [ 74] = 74
	INVALID_LETTER, // [ 75] = 75
	INVALID_LETTER, // [ 76] = 76
	INVALID_LETTER, // [ 77] = 77
	INVALID_LETTER, // [ 78] = 78
	INVALID_LETTER, // [ 79] = 79
	INVALID_LETTER, // [ 80] = 80
	INVALID_LETTER, // [ 81] = 81
	INVALID_LETTER, // [ 82] = 82
	INVALID_LETTER, // [ 83] = 83
	3  ,            // [ 84] = T (Nucleotide)
	3  ,            // [ 85] = U (Nucleotide)
	INVALID_LETTER, // [ 86] = 86
	INVALID_LETTER, // [ 87] = 87
	INVALID_LETTER, // [ 88] = 88
	INVALID_LETTER, // [ 89] = 89
	INVALID_LETTER, // [ 90] = 90
	INVALID_LETTER, // [ 91] = 91
	INVALID_LETTER, // [ 92] = 92
	INVALID_LETTER, // [ 93] = 93
	INVALID_LETTER, // [ 94] = 94
	INVALID_LETTER, // [ 95] = 95
	INVALID_LETTER, // [ 96] = 96
	0  ,            // [ 97] = a (Nucleotide)
	INVALID_LETTER, // [ 98] = 98
	1  ,            // [ 99] = c (Nucleotide)
	INVALID_LETTER, // [100] = 100
	INVALID_LETTER, // [101] = 101
	INVALID_LETTER, // [102] = 102
	2  ,            // [103] = g (Nucleotide)
	INVALID_LETTER, // [104] = 104
	INVALID_LETTER, // [105] = 105
	INVALID_LETTER, // [106] = 106
	INVALID_LETTER, // [107] = 107
	INVALID_LETTER, // [108] = 108
	INVALID_LETTER, // [109] = 109
	INVALID_LETTER, // [110] = 110
	INVALID_LETTER, // [111] = 111
	INVALID_LETTER, // [112] = 112
	INVALID_LETTER, // [113] = 113
	INVALID_LETTER, // [114] = 114
	INVALID_LETTER, // [115] = 115
	3  ,            // [116] = t (Nucleotide)
	3  ,            // [117] = u (Nucleotide)
	INVALID_LETTER, // [118] = 118
	INVALID_LETTER, // [119] = 119
	INVALID_LETTER, // [120] = 120
	INVALID_LETTER, // [121] = 121
	INVALID_LETTER, // [122] = 122
	INVALID_LETTER, // [123] = 123
	INVALID_LETTER, // [124] = 124
	INVALID_LETTER, // [125] = 125
	INVALID_LETTER, // [126] = 126
	INVALID_LETTER, // [127] = 0x7f
	INVALID_LETTER, // [128] = 0x80
	INVALID_LETTER, // [129] = 0x81
	INVALID_LETTER, // [130] = 0x82
	INVALID_LETTER, // [131] = 0x83
	INVALID_LETTER, // [132] = 0x84
	INVALID_LETTER, // [133] = 0x85
	INVALID_LETTER, // [134] = 0x86
	INVALID_LETTER, // [135] = 0x87
	INVALID_LETTER, // [136] = 0x88
	INVALID_LETTER, // [137] = 0x89
	INVALID_LETTER, // [138] = 0x8a
	INVALID_LETTER, // [139] = 0x8b
	INVALID_LETTER, // [140] = 0x8c
	INVALID_LETTER, // [141] = 0x8d
	INVALID_LETTER, // [142] = 0x8e
	INVALID_LETTER, // [143] = 0x8f
	INVALID_LETTER, // [144] = 0x90
	INVALID_LETTER, // [145] = 0x91
	INVALID_LETTER, // [146] = 0x92
	INVALID_LETTER, // [147] = 0x93
	INVALID_LETTER, // [148] = 0x94
	INVALID_LETTER, // [149] = 0x95
	INVALID_LETTER, // [150] = 0x96
	INVALID_LETTER, // [151] = 0x97
	INVALID_LETTER, // [152] = 0x98
	INVALID_LETTER, // [153] = 0x99
	INVALID_LETTER, // [154] = 0x9a
	INVALID_LETTER, // [155] = 0x9b
	INVALID_LETTER, // [156] = 0x9c
	INVALID_LETTER, // [157] = 0x9d
	INVALID_LETTER, // [158] = 0x9e
	INVALID_LETTER, // [159] = 0x9f
	INVALID_LETTER, // [160] = 0xa0
	INVALID_LETTER, // [161] = 0xa1
	INVALID_LETTER, // [162] = 0xa2
	INVALID_LETTER, // [163] = 0xa3
	INVALID_LETTER, // [164] = 0xa4
	INVALID_LETTER, // [165] = 0xa5
	INVALID_LETTER, // [166] = 0xa6
	INVALID_LETTER, // [167] = 0xa7
	INVALID_LETTER, // [168] = 0xa8
	INVALID_LETTER, // [169] = 0xa9
	INVALID_LETTER, // [170] = 0xaa
	INVALID_LETTER, // [171] = 0xab
	INVALID_LETTER, // [172] = 0xac
	INVALID_LETTER, // [173] = 0xad
	INVALID_LETTER, // [174] = 0xae
	INVALID_LETTER, // [175] = 0xaf
	INVALID_LETTER, // [176] = 0xb0
	INVALID_LETTER, // [177] = 0xb1
	INVALID_LETTER, // [178] = 0xb2
	INVALID_LETTER, // [179] = 0xb3
	INVALID_LETTER, // [180] = 0xb4
	INVALID_LETTER, // [181] = 0xb5
	INVALID_LETTER, // [182] = 0xb6
	INVALID_LETTER, // [183] = 0xb7
	INVALID_LETTER, // [184] = 0xb8
	INVALID_LETTER, // [185] = 0xb9
	INVALID_LETTER, // [186] = 0xba
	INVALID_LETTER, // [187] = 0xbb
	INVALID_LETTER, // [188] = 0xbc
	INVALID_LETTER, // [189] = 0xbd
	INVALID_LETTER, // [190] = 0xbe
	INVALID_LETTER, // [191] = 0xbf
	INVALID_LETTER, // [192] = 0xc0
	INVALID_LETTER, // [193] = 0xc1
	INVALID_LETTER, // [194] = 0xc2
	INVALID_LETTER, // [195] = 0xc3
	INVALID_LETTER, // [196] = 0xc4
	INVALID_LETTER, // [197] = 0xc5
	INVALID_LETTER, // [198] = 0xc6
	INVALID_LETTER, // [199] = 0xc7
	INVALID_LETTER, // [200] = 0xc8
	INVALID_LETTER, // [201] = 0xc9
	INVALID_LETTER, // [202] = 0xca
	INVALID_LETTER, // [203] = 0xcb
	INVALID_LETTER, // [204] = 0xcc
	INVALID_LETTER, // [205] = 0xcd
	INVALID_LETTER, // [206] = 0xce
	INVALID_LETTER, // [207] = 0xcf
	INVALID_LETTER, // [208] = 0xd0
	INVALID_LETTER, // [209] = 0xd1
	INVALID_LETTER, // [210] = 0xd2
	INVALID_LETTER, // [211] = 0xd3
	INVALID_LETTER, // [212] = 0xd4
	INVALID_LETTER, // [213] = 0xd5
	INVALID_LETTER, // [214] = 0xd6
	INVALID_LETTER, // [215] = 0xd7
	INVALID_LETTER, // [216] = 0xd8
	INVALID_LETTER, // [217] = 0xd9
	INVALID_LETTER, // [218] = 0xda
	INVALID_LETTER, // [219] = 0xdb
	INVALID_LETTER, // [220] = 0xdc
	INVALID_LETTER, // [221] = 0xdd
	INVALID_LETTER, // [222] = 0xde
	INVALID_LETTER, // [223] = 0xdf
	INVALID_LETTER, // [224] = 0xe0
	INVALID_LETTER, // [225] = 0xe1
	INVALID_LETTER, // [226] = 0xe2
	INVALID_LETTER, // [227] = 0xe3
	INVALID_LETTER, // [228] = 0xe4
	INVALID_LETTER, // [229] = 0xe5
	INVALID_LETTER, // [230] = 0xe6
	INVALID_LETTER, // [231] = 0xe7
	INVALID_LETTER, // [232] = 0xe8
	INVALID_LETTER, // [233] = 0xe9
	INVALID_LETTER, // [234] = 0xea
	INVALID_LETTER, // [235] = 0xeb
	INVALID_LETTER, // [236] = 0xec
	INVALID_LETTER, // [237] = 0xed
	INVALID_LETTER, // [238] = 0xee
	INVALID_LETTER, // [239] = 0xef
	INVALID_LETTER, // [240] = 0xf0
	INVALID_LETTER, // [241] = 0xf1
	INVALID_LETTER, // [242] = 0xf2
	INVALID_LETTER, // [243] = 0xf3
	INVALID_LETTER, // [244] = 0xf4
	INVALID_LETTER, // [245] = 0xf5
	INVALID_LETTER, // [246] = 0xf6
	INVALID_LETTER, // [247] = 0xf7
	INVALID_LETTER, // [248] = 0xf8
	INVALID_LETTER, // [249] = 0xf9
	INVALID_LETTER, // [250] = 0xfa
	INVALID_LETTER, // [251] = 0xfb
	INVALID_LETTER, // [252] = 0xfc
	INVALID_LETTER, // [253] = 0xfd
	INVALID_LETTER, // [254] = 0xfe
	INVALID_LETTER, // [255] = 0xff
	};

bool g_IsNucleoChar[256] =
	{
	false, // [  0] 0x00
	false, // [  1] 0x01
	false, // [  2] 0x02
	false, // [  3] 0x03
	false, // [  4] 0x04
	false, // [  5] 0x05
	false, // [  6] 0x06
	false, // [  7] 0x07
	false, // [  8] 0x08
	false, // [  9] 0x09
	false, // [ 10] 0x0a
	false, // [ 11] 0x0b
	false, // [ 12] 0x0c
	false, // [ 13] 0x0d
	false, // [ 14] 0x0e
	false, // [ 15] 0x0f
	false, // [ 16] 0x10
	false, // [ 17] 0x11
	false, // [ 18] 0x12
	false, // [ 19] 0x13
	false, // [ 20] 0x14
	false, // [ 21] 0x15
	false, // [ 22] 0x16
	false, // [ 23] 0x17
	false, // [ 24] 0x18
	false, // [ 25] 0x19
	false, // [ 26] 0x1a
	false, // [ 27] 0x1b
	false, // [ 28] 0x1c
	false, // [ 29] 0x1d
	false, // [ 30] 0x1e
	false, // [ 31] 0x1f
	false, // [ 32] ' '
	false, // [ 33] '!'
	false, // [ 34] '"'
	false, // [ 35] '#'
	false, // [ 36] '$'
	false, // [ 37] '%'
	false, // [ 38] '&'
	false, // [ 39] '''
	false, // [ 40] '('
	false, // [ 41] ')'
	false, // [ 42] '*'
	false, // [ 43] '+'
	false, // [ 44] ','
	false, // [ 45] '-'
	false, // [ 46] '.'
	false, // [ 47] '/'
	false, // [ 48] '0'
	false, // [ 49] '1'
	false, // [ 50] '2'
	false, // [ 51] '3'
	false, // [ 52] '4'
	false, // [ 53] '5'
	false, // [ 54] '6'
	false, // [ 55] '7'
	false, // [ 56] '8'
	false, // [ 57] '9'
	false, // [ 58] ':'
	false, // [ 59] ';'
	false, // [ 60] '<'
	false, // [ 61] '='
	false, // [ 62] '>'
	false, // [ 63] '?'
	false, // [ 64] '@'
	true,  // [ 65] 'A' (Nucleotide)
	false, // [ 66] 'B'
	true,  // [ 67] 'C' (Nucleotide)
	false, // [ 68] 'D'
	false, // [ 69] 'E'
	false, // [ 70] 'F'
	true,  // [ 71] 'G' (Nucleotide)
	false, // [ 72] 'H'
	false, // [ 73] 'I'
	false, // [ 74] 'J'
	false, // [ 75] 'K'
	false, // [ 76] 'L'
	false, // [ 77] 'M'
	true,  // [ 78] 'N' (Nucleotide)
	false, // [ 79] 'O'
	false, // [ 80] 'P'
	false, // [ 81] 'Q'
	false, // [ 82] 'R'
	false, // [ 83] 'S'
	true,  // [ 84] 'T' (Nucleotide)
	true,  // [ 85] 'U' (Nucleotide)
	false, // [ 86] 'V'
	false, // [ 87] 'W'
	false, // [ 88] 'X'
	false, // [ 89] 'Y'
	false, // [ 90] 'Z'
	false, // [ 91] '['
	false, // [ 92] '\'
	false, // [ 93] ']'
	false, // [ 94] '^'
	false, // [ 95] '_'
	false, // [ 96] '`'
	true,  // [ 97] 'A' (Nucleotide)
	false, // [ 98] 'B'
	true,  // [ 99] 'C' (Nucleotide)
	false, // [100] 'D'
	false, // [101] 'E'
	false, // [102] 'F'
	true,  // [103] 'G' (Nucleotide)
	false, // [104] 'H'
	false, // [105] 'I'
	false, // [106] 'J'
	false, // [107] 'K'
	false, // [108] 'L'
	false, // [109] 'M'
	true,  // [110] 'N' (Nucleotide)
	false, // [111] 'O'
	false, // [112] 'P'
	false, // [113] 'Q'
	false, // [114] 'R'
	false, // [115] 'S'
	true,  // [116] 'T' (Nucleotide)
	true,  // [117] 'U' (Nucleotide)
	false, // [118] 'V'
	false, // [119] 'W'
	false, // [120] 'X'
	false, // [121] 'Y'
	false, // [122] 'Z'
	false, // [123] '{'
	false, // [124] '|'
	false, // [125] '}'
	false, // [126] '~'
	false, // [127] 0x7f
	false, // [128] 0x80
	false, // [129] 0x81
	false, // [130] 0x82
	false, // [131] 0x83
	false, // [132] 0x84
	false, // [133] 0x85
	false, // [134] 0x86
	false, // [135] 0x87
	false, // [136] 0x88
	false, // [137] 0x89
	false, // [138] 0x8a
	false, // [139] 0x8b
	false, // [140] 0x8c
	false, // [141] 0x8d
	false, // [142] 0x8e
	false, // [143] 0x8f
	false, // [144] 0x90
	false, // [145] 0x91
	false, // [146] 0x92
	false, // [147] 0x93
	false, // [148] 0x94
	false, // [149] 0x95
	false, // [150] 0x96
	false, // [151] 0x97
	false, // [152] 0x98
	false, // [153] 0x99
	false, // [154] 0x9a
	false, // [155] 0x9b
	false, // [156] 0x9c
	false, // [157] 0x9d
	false, // [158] 0x9e
	false, // [159] 0x9f
	false, // [160] 0xa0
	false, // [161] 0xa1
	false, // [162] 0xa2
	false, // [163] 0xa3
	false, // [164] 0xa4
	false, // [165] 0xa5
	false, // [166] 0xa6
	false, // [167] 0xa7
	false, // [168] 0xa8
	false, // [169] 0xa9
	false, // [170] 0xaa
	false, // [171] 0xab
	false, // [172] 0xac
	false, // [173] 0xad
	false, // [174] 0xae
	false, // [175] 0xaf
	false, // [176] 0xb0
	false, // [177] 0xb1
	false, // [178] 0xb2
	false, // [179] 0xb3
	false, // [180] 0xb4
	false, // [181] 0xb5
	false, // [182] 0xb6
	false, // [183] 0xb7
	false, // [184] 0xb8
	false, // [185] 0xb9
	false, // [186] 0xba
	false, // [187] 0xbb
	false, // [188] 0xbc
	false, // [189] 0xbd
	false, // [190] 0xbe
	false, // [191] 0xbf
	false, // [192] 0xc0
	false, // [193] 0xc1
	false, // [194] 0xc2
	false, // [195] 0xc3
	false, // [196] 0xc4
	false, // [197] 0xc5
	false, // [198] 0xc6
	false, // [199] 0xc7
	false, // [200] 0xc8
	false, // [201] 0xc9
	false, // [202] 0xca
	false, // [203] 0xcb
	false, // [204] 0xcc
	false, // [205] 0xcd
	false, // [206] 0xce
	false, // [207] 0xcf
	false, // [208] 0xd0
	false, // [209] 0xd1
	false, // [210] 0xd2
	false, // [211] 0xd3
	false, // [212] 0xd4
	false, // [213] 0xd5
	false, // [214] 0xd6
	false, // [215] 0xd7
	false, // [216] 0xd8
	false, // [217] 0xd9
	false, // [218] 0xda
	false, // [219] 0xdb
	false, // [220] 0xdc
	false, // [221] 0xdd
	false, // [222] 0xde
	false, // [223] 0xdf
	false, // [224] 0xe0
	false, // [225] 0xe1
	false, // [226] 0xe2
	false, // [227] 0xe3
	false, // [228] 0xe4
	false, // [229] 0xe5
	false, // [230] 0xe6
	false, // [231] 0xe7
	false, // [232] 0xe8
	false, // [233] 0xe9
	false, // [234] 0xea
	false, // [235] 0xeb
	false, // [236] 0xec
	false, // [237] 0xed
	false, // [238] 0xee
	false, // [239] 0xef
	false, // [240] 0xf0
	false, // [241] 0xf1
	false, // [242] 0xf2
	false, // [243] 0xf3
	false, // [244] 0xf4
	false, // [245] 0xf5
	false, // [246] 0xf6
	false, // [247] 0xf7
	false, // [248] 0xf8
	false, // [249] 0xf9
	false, // [250] 0xfa
	false, // [251] 0xfb
	false, // [252] 0xfc
	false, // [253] 0xfd
	false, // [254] 0xfe
	false, // [255] 0xff
	};

bool g_IsACGTU[256] =
	{
	false, // [  0] 0x00
	false, // [  1] 0x01
	false, // [  2] 0x02
	false, // [  3] 0x03
	false, // [  4] 0x04
	false, // [  5] 0x05
	false, // [  6] 0x06
	false, // [  7] 0x07
	false, // [  8] 0x08
	false, // [  9] 0x09
	false, // [ 10] 0x0a
	false, // [ 11] 0x0b
	false, // [ 12] 0x0c
	false, // [ 13] 0x0d
	false, // [ 14] 0x0e
	false, // [ 15] 0x0f
	false, // [ 16] 0x10
	false, // [ 17] 0x11
	false, // [ 18] 0x12
	false, // [ 19] 0x13
	false, // [ 20] 0x14
	false, // [ 21] 0x15
	false, // [ 22] 0x16
	false, // [ 23] 0x17
	false, // [ 24] 0x18
	false, // [ 25] 0x19
	false, // [ 26] 0x1a
	false, // [ 27] 0x1b
	false, // [ 28] 0x1c
	false, // [ 29] 0x1d
	false, // [ 30] 0x1e
	false, // [ 31] 0x1f
	false, // [ 32] ' '
	false, // [ 33] '!'
	false, // [ 34] '"'
	false, // [ 35] '#'
	false, // [ 36] '$'
	false, // [ 37] '%'
	false, // [ 38] '&'
	false, // [ 39] '''
	false, // [ 40] '('
	false, // [ 41] ')'
	false, // [ 42] '*'
	false, // [ 43] '+'
	false, // [ 44] ','
	false, // [ 45] '-'
	false, // [ 46] '.'
	false, // [ 47] '/'
	false, // [ 48] '0'
	false, // [ 49] '1'
	false, // [ 50] '2'
	false, // [ 51] '3'
	false, // [ 52] '4'
	false, // [ 53] '5'
	false, // [ 54] '6'
	false, // [ 55] '7'
	false, // [ 56] '8'
	false, // [ 57] '9'
	false, // [ 58] ':'
	false, // [ 59] ';'
	false, // [ 60] '<'
	false, // [ 61] '='
	false, // [ 62] '>'
	false, // [ 63] '?'
	false, // [ 64] '@'
	true,  // [ 65] 'A' (ACGT)
	false, // [ 66] 'B'
	true,  // [ 67] 'C' (ACGT)
	false, // [ 68] 'D'
	false, // [ 69] 'E'
	false, // [ 70] 'F'
	true,  // [ 71] 'G' (ACGT)
	false, // [ 72] 'H'
	false, // [ 73] 'I'
	false, // [ 74] 'J'
	false, // [ 75] 'K'
	false, // [ 76] 'L'
	false, // [ 77] 'M'
	false, // [ 78] 'N'
	false, // [ 79] 'O'
	false, // [ 80] 'P'
	false, // [ 81] 'Q'
	false, // [ 82] 'R'
	false, // [ 83] 'S'
	true,  // [ 84] 'T' (ACGT)
	true,  // [ 85] 'U' (ACGT)
	false, // [ 86] 'V'
	false, // [ 87] 'W'
	false, // [ 88] 'X'
	false, // [ 89] 'Y'
	false, // [ 90] 'Z'
	false, // [ 91] '['
	false, // [ 92] '\'
	false, // [ 93] ']'
	false, // [ 94] '^'
	false, // [ 95] '_'
	false, // [ 96] '`'
	true,  // [ 97] 'A' (ACGT)
	false, // [ 98] 'B'
	true,  // [ 99] 'C' (ACGT)
	false, // [100] 'D'
	false, // [101] 'E'
	false, // [102] 'F'
	true,  // [103] 'G' (ACGT)
	false, // [104] 'H'
	false, // [105] 'I'
	false, // [106] 'J'
	false, // [107] 'K'
	false, // [108] 'L'
	false, // [109] 'M'
	false, // [110] 'N'
	false, // [111] 'O'
	false, // [112] 'P'
	false, // [113] 'Q'
	false, // [114] 'R'
	false, // [115] 'S'
	true,  // [116] 'T' (ACGT)
	true,  // [117] 'U' (ACGT)
	false, // [118] 'V'
	false, // [119] 'W'
	false, // [120] 'X'
	false, // [121] 'Y'
	false, // [122] 'Z'
	false, // [123] '{'
	false, // [124] '|'
	false, // [125] '}'
	false, // [126] '~'
	false, // [127] 0x7f
	false, // [128] 0x80
	false, // [129] 0x81
	false, // [130] 0x82
	false, // [131] 0x83
	false, // [132] 0x84
	false, // [133] 0x85
	false, // [134] 0x86
	false, // [135] 0x87
	false, // [136] 0x88
	false, // [137] 0x89
	false, // [138] 0x8a
	false, // [139] 0x8b
	false, // [140] 0x8c
	false, // [141] 0x8d
	false, // [142] 0x8e
	false, // [143] 0x8f
	false, // [144] 0x90
	false, // [145] 0x91
	false, // [146] 0x92
	false, // [147] 0x93
	false, // [148] 0x94
	false, // [149] 0x95
	false, // [150] 0x96
	false, // [151] 0x97
	false, // [152] 0x98
	false, // [153] 0x99
	false, // [154] 0x9a
	false, // [155] 0x9b
	false, // [156] 0x9c
	false, // [157] 0x9d
	false, // [158] 0x9e
	false, // [159] 0x9f
	false, // [160] 0xa0
	false, // [161] 0xa1
	false, // [162] 0xa2
	false, // [163] 0xa3
	false, // [164] 0xa4
	false, // [165] 0xa5
	false, // [166] 0xa6
	false, // [167] 0xa7
	false, // [168] 0xa8
	false, // [169] 0xa9
	false, // [170] 0xaa
	false, // [171] 0xab
	false, // [172] 0xac
	false, // [173] 0xad
	false, // [174] 0xae
	false, // [175] 0xaf
	false, // [176] 0xb0
	false, // [177] 0xb1
	false, // [178] 0xb2
	false, // [179] 0xb3
	false, // [180] 0xb4
	false, // [181] 0xb5
	false, // [182] 0xb6
	false, // [183] 0xb7
	false, // [184] 0xb8
	false, // [185] 0xb9
	false, // [186] 0xba
	false, // [187] 0xbb
	false, // [188] 0xbc
	false, // [189] 0xbd
	false, // [190] 0xbe
	false, // [191] 0xbf
	false, // [192] 0xc0
	false, // [193] 0xc1
	false, // [194] 0xc2
	false, // [195] 0xc3
	false, // [196] 0xc4
	false, // [197] 0xc5
	false, // [198] 0xc6
	false, // [199] 0xc7
	false, // [200] 0xc8
	false, // [201] 0xc9
	false, // [202] 0xca
	false, // [203] 0xcb
	false, // [204] 0xcc
	false, // [205] 0xcd
	false, // [206] 0xce
	false, // [207] 0xcf
	false, // [208] 0xd0
	false, // [209] 0xd1
	false, // [210] 0xd2
	false, // [211] 0xd3
	false, // [212] 0xd4
	false, // [213] 0xd5
	false, // [214] 0xd6
	false, // [215] 0xd7
	false, // [216] 0xd8
	false, // [217] 0xd9
	false, // [218] 0xda
	false, // [219] 0xdb
	false, // [220] 0xdc
	false, // [221] 0xdd
	false, // [222] 0xde
	false, // [223] 0xdf
	false, // [224] 0xe0
	false, // [225] 0xe1
	false, // [226] 0xe2
	false, // [227] 0xe3
	false, // [228] 0xe4
	false, // [229] 0xe5
	false, // [230] 0xe6
	false, // [231] 0xe7
	false, // [232] 0xe8
	false, // [233] 0xe9
	false, // [234] 0xea
	false, // [235] 0xeb
	false, // [236] 0xec
	false, // [237] 0xed
	false, // [238] 0xee
	false, // [239] 0xef
	false, // [240] 0xf0
	false, // [241] 0xf1
	false, // [242] 0xf2
	false, // [243] 0xf3
	false, // [244] 0xf4
	false, // [245] 0xf5
	false, // [246] 0xf6
	false, // [247] 0xf7
	false, // [248] 0xf8
	false, // [249] 0xf9
	false, // [250] 0xfa
	false, // [251] 0xfb
	false, // [252] 0xfc
	false, // [253] 0xfd
	false, // [254] 0xfe
	false, // [255] 0xff
	};
