// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// summarize_fasta
Rcpp::DataFrame summarize_fasta(Rcpp::DataFrame& summary_report, Rcpp::IntegerVector& count, int processors);
RcppExport SEXP _rchime_summarize_fasta(SEXP summary_reportSEXP, SEXP countSEXP, SEXP processorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type summary_report(summary_reportSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type count(countSEXP);
    Rcpp::traits::input_parameter< int >::type processors(processorsSEXP);
    rcpp_result_gen = Rcpp::wrap(summarize_fasta(summary_report, count, processors));
    return rcpp_result_gen;
END_RCPP
}
// rchimeReference
Rcpp::List rchimeReference(Rcpp::Environment& dataset, Rcpp::CharacterVector& ref_names, Rcpp::CharacterVector& ref_seqs, Rcpp::List options);
RcppExport SEXP _rchime_rchimeReference(SEXP datasetSEXP, SEXP ref_namesSEXP, SEXP ref_seqsSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector& >::type ref_names(ref_namesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector& >::type ref_seqs(ref_seqsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rchimeReference(dataset, ref_names, ref_seqs, options));
    return rcpp_result_gen;
END_RCPP
}
// rchimeDenovo
Rcpp::List rchimeDenovo(Rcpp::Environment& dataset, Rcpp::List options);
RcppExport SEXP _rchime_rchimeDenovo(SEXP datasetSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rchimeDenovo(dataset, options));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_rchime_summarize_fasta", (DL_FUNC) &_rchime_summarize_fasta, 3},
    {"_rchime_rchimeReference", (DL_FUNC) &_rchime_rchimeReference, 4},
    {"_rchime_rchimeDenovo", (DL_FUNC) &_rchime_rchimeDenovo, 2},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rchime(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
