# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title chimeraUchimeReference
#' @name chimeraUchimeReference
#' @rdname chimeraUchimeReference
#' @param dataset R6 'sequence_dataset' object containing sequence data
#' @param reference R6 'sequence_dataset' object containing sequence data
#' @param options list containing parameter options
#' @seealso [chimera_uchime()]
#' @description detects and removes chimeras from your data using a reference
#'  dataset.
chimeraUchimeReference <- function(dataset, reference, options) {
    .Call(`_rchime_chimeraUchimeReference`, dataset, reference, options)
}

#' @title chimeraUchime
#' @name chimeraUchime
#' @rdname chimeraUchime
#' @param dataset R6 'sequence_dataset' object containing sequence data
#' @param options list containing parameter options
#' @seealso [chimera_uchime()]
#' @description detects and removes chimeras from your data using a denovo
#' approach.
chimeraUchime <- function(dataset, options) {
    .Call(`_rchime_chimeraUchime`, dataset, options)
}

