# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Detects chimeras using a reference based approach
#' @name rchimeReference
#' @rdname rchimeReference
#'
#' @description detects chimeras in your data using a reference based approach.
#'
#' @param sequence_names, vector of strings containing sequence names
#' @param sequences, vector of strings containing sequence nucleotide data
#' @param reference_names, vector of strings containing reference sequences names
#' @param reference_sequences, vector of strings containing reference sequences
#' @param options list containing parameter options. Default = NULL.
#'
#' @examples
#'
#' # Read in data.frames containing sequence data
#'
#' fasta_data <- readRDS(rchime_example("miseq_fasta.rds"))
#' reference_data <- readRDS(rchime_example("reference.rds"))
#'
#' # Detect chimeras
#'
#' results <- rchimeReference(sequence_names = fasta_data$sequence_names,
#'                            sequences = fasta_data$sequences,
#'                            reference_names = reference_data$sequence_names,
#'                            reference_sequences = reference_data$sequences)
#'
#' @seealso [rchime()]
rchimeReference <- function(sequence_names, sequences, reference_names, reference_sequences, options = NULL) {
    .Call(`_rchime_rchimeReference`, sequence_names, sequences, reference_names, reference_sequences, options)
}

#' @title Detects chimeras using a denovo approach
#' @name rchimeDenovoSingleSample
#' @rdname rchimeDenovoSingleSample
#'
#' @description detects chimeras in your data using a denovo approach.
#'
#' @param sequence_names, vector of strings containing sequence names
#' @param sequences, vector of strings containing sequence nucleotide data
#' @param abundances, vector of sequence abundances
#' @param options list containing parameter options. Default = NULL.
#'
#' @examples
#'
#' # Read in data.frames containing sequence and abundance data
#'
#' fasta_data <- readRDS(rchime_example("miseq_fasta.rds"))
#' abundance_data <- readRDS(rchime_example("single_sample_abundance.rds"))
#'
#' # Detect chimeras
#'
#' results <- rchimeDenovoSingleSample(sequence_names = fasta_data$sequence_names,
#'                                     sequences = fasta_data$sequences,
#'                                     abundances = abundance_data$abundances)
#'
#' @seealso [rchime()]
rchimeDenovoSingleSample <- function(sequence_names, sequences, abundances, options = NULL) {
    .Call(`_rchime_rchimeDenovoSingleSample`, sequence_names, sequences, abundances, options)
}

#' @title Detects chimeras using a denovo method processing by sample.
#' @name rchimeDenovo
#' @rdname rchimeDenovo
#'
#' @param sequence_names, 2D vector of strings containing sequence names parsed by sample
#' @param sequences, 2D vector of strings containing sequence nucleotide data  parsed by sample
#' @param abundances, 2D vector of sequence abundances parsed by sample
#' @param options list containing parameter options. Default = NULL.
#'
#' @examples
#'
#' # Read in data.frames containing sequence and abundance data
#'
#' sequence_names <- readRDS(rchime_example("miseq_names_by_sample.rds"))
#' sequences <- readRDS(rchime_example("miseq_sequences_by_sample.rds"))
#' abundances <- readRDS(rchime_example("miseq_abundance_by_sample.rds"))
#'
#' # Detect chimeras
#'
#' options <- rchime_options(dereplicate = TRUE)
#' results <- rchimeDenovo(sequence_names = sequence_names,
#'                         sequences = sequences,
#'                         abundances = abundances,
#'                         options)
#'
#' @seealso [rchime()]
#' @description detects chimeras from your data using a denovo method processing by sample.
#' @returns list()
rchimeDenovo <- function(sequence_names, sequences, abundances, options = NULL) {
    .Call(`_rchime_rchimeDenovo`, sequence_names, sequences, abundances, options)
}

