# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rchimeReference
#' @name rchimeReference
#' @rdname rchimeReference
#' @param sequence_names, vector of strings containing sequence names
#' @param sequences, vector of strings containing sequence nucleotide data
#' @param abundances, vector of sequence abundances
#' @param reference_names, vector of strings containing reference sequences names
#' @param reference_sequences, vector of strings containing reference sequences
#' @param options list containing parameter options
#' @seealso [rchime()]
#' @description detects chimeras from your data using a reference dataset.
rchimeReference <- function(sequence_names, sequences, abundances, reference_names, reference_sequences, options) {
    .Call(`_rchime_rchimeReference`, sequence_names, sequences, abundances, reference_names, reference_sequences, options)
}

#' @title rchimeDenovoSingleSample
#' @name rchimeDenovoSingleSample
#' @rdname rchimeDenovoSingleSample
#' @param sequence_names, vector of strings containing sequence names
#' @param sequences, vector of strings containing sequence nucleotide data
#' @param abundances, vector of sequence abundances
#' @param options list containing parameter options
#' @seealso [rchime()]
#' @description detects chimeras from your data using a denovo method.
rchimeDenovoSingleSample <- function(sequence_names, sequences, abundances, options) {
    .Call(`_rchime_rchimeDenovoSingleSample`, sequence_names, sequences, abundances, options)
}

#' @title rchimeDenovo
#' @name rchimeDenovo
#' @rdname rchimeDenovo
#' @param sequence_names, 2D vector of strings containing sequence names parsed by sample
#' @param sequences, 2D vector of strings containing sequence nucleotide data  parsed by sample
#' @param abundances, 2D vector of sequence abundances parsed by sample
#' @param options list containing parameter options
#' @seealso [rchime()]
#' @description detects chimeras from your data using a denovo method processing by sample.
rchimeDenovo <- function(sequence_names, sequences, abundances, options) {
    .Call(`_rchime_rchimeDenovo`, sequence_names, sequences, abundances, options)
}

